formatter: "markdown table"

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sections:
  inputs: true
  outputs: true
  requirements: true
  providers: true
  modules: true
  resources: false

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  indent: 2
  required: true
  sensitive: true
  type: true
